// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ADecryptMessage(arg1:string,arg2:string):Promise<Array<string>>;

export function AEncryptMessage(arg1:string,arg2:string):Promise<Array<string>>;

export function AGenerateKeyPair():Promise<Array<string>>;
