// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ADecryptMessage(arg1, arg2) {
  return window['go']['main']['App']['ADecryptMessage'](arg1, arg2);
}

export function AEncryptMessage(arg1, arg2) {
  return window['go']['main']['App']['AEncryptMessage'](arg1, arg2);
}

export function AGenerateKeyPair() {
  return window['go']['main']['App']['AGenerateKeyPair']();
}
